### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by ghost** [sbcshop/Raspberry-Pi-Pico-RFID-Expansion#1]
I get `AttributeError: 'NoneType' object has no attribute 'decode'` when running the example on my Pico.

The culprit is the second line.
```python
     command= uart.read(12)
     command.decode("utf-8")
```

The output of command is always None, even with a tag present.

**Comment by sbcshop** [comment]
Hi Fossil01,

Greetings of the day!

Thank you so much for acknowledging the above issue. Our team has looked into this issue and resolved the same. you can check the updated code on "Board.Test.py". If you find any other query kindly let us know.

fixed the issue by putting command.decode("utf-8") under if condition.

```python
while True:
    #uart.write('h')
    command= uart.read(12)
    
    if command:
        print(command.decode("utf-8"))
```

Thanks

**Comment by ghost** [comment]
Thanks, that was quick. I thought I did the same when testing but I mist have made a typo. Seems to not throw errors now, but it's also nog reading MiFare Classic cards still. No buzzer either.

I just get "aaaa" looped in console, but nothing when I present a card. Nothing in the OLED screen either. The screen does work when I put something outside the if condition though.

All yellow jumpers are connected.

[EDIT] It does work with the bundled card and tag. Just checked the specs, I am an idiot and did not see it only did 125khz tags.

**Comment by sbcshop** [comment]
Hi Fossil01,

Mifare RFID Cards / Tags are Not compatible with this RFID Expansion Board, Please use 125 kHz frequency-based cards with this reader. The buzzer and Oled will work once you scan a valid 125 kHz card over it.
